#Training properties
#Mon May 18 23:30:43 CEST 2026
batchMode=false
batchSize=
createTrainingSnapshots=false
earlyStopping=true
earlyStopping.checkpointEpochs=5
earlyStopping.minDelta=0.001
earlyStopping.patience=8
evaluationMetrics=Classification
learningRate=0.0001
maxEpochs=25
maxError=0.01
momentum=0
networkArchitecture=networkArch1.json
optimizationAlgorithm=Adam
randomSeed=123
snapshotEpochs=10
trainValTestSplit=60,10,30
trainingSet=NewImageDataset.properties
