#Data set properties
#Mon May 18 23:30:42 CEST 2026
augmentImages=false
dataSet.balanceUpsample=false
dataSet.imageDir=C\:\\Users\\Zoran\\Downloads\\archive300x4\\Training
dataSet.imageHeight=64
dataSet.imageIndexFile=C\:\\Users\\Zoran\\Downloads\\archive300x4\\Training/index.txt
dataSet.imageResizeStrategy=resizeAndCenter
dataSet.imageWidth=64
dataSet.invertPixels=false
dataSet.labelsFile=C\:\\Users\\Zoran\\Downloads\\archive300x4\\Training/labels.txt
dataSet.labelsNum=4
dataSet.name=NewImageDataset
dataSet.type=images
dataSet.zeroMean=false
